### ISSUE TITLE
Validation improvement: Unknown parent entity

### ISSUE THREAD

**Issue by alexandervlasenko** [NoxOrg/Nox.Lib.V6#133]
Configuration validation should be improved, so in case of non-existing parent entity we get a meaningful validation exception. Currently we get exception in MetaService in entities.First(x => x.Name.Equals(parent, StringComparison.OrdinalIgnoreCase)).RelatedChildren.

**Comment by ghost** [comment]
I will take this

**Comment by ghost** [comment]
Resolved
