### ISSUE TITLE
Sample project build from nuget Nox.Lib package doesn't reflect context-specific Swagger endpoints

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox.Lib.V6#148]
![image](https://user-images.githubusercontent.com/64355398/222097363-8cb4f5a6-141c-4917-8097-ad7c27fa12e3.png)

**Comment by ghost** [comment]
Hello @Mornevanzyl !

Can you specify Nox packages versions that you've used, please?
Also, write the scenario you've used. Did you import Nox packages into a separate project?
Did you add OData Swagger Filter we currently have for it?

```
builder.Services.AddSwaggerGen(cfg =>
{
    //Add this to ensure swagger document is correctly annotated
    cfg.EnableAnnotations();

    cfg.DocumentFilter<ODataCustomSwaggerFilter>();
});
...
...
ODataCustomSwaggerFilter.SetDynamicService(app.Services.GetService<IDynamicService>());
ODataCustomSwaggerFilter.SetLogger(app.Services.GetService<ILogger<ODataCustomSwaggerFilter>>());
```

**Comment by ghost** [comment]
The PR was merged, closing the issue
