### ISSUE TITLE
[Nox.Cli] Review workflow syntax alignment against Git workflows

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox.Lib.V6#164]
Just something I picked up whilst comparing Nox vs. Git workflow implementations
 
**Key difference/takeaway:**
```.uses``` and ```.with``` is used by Git on a ```.job``` level and by Nox on a ```.step``` level
 
**More detail:**
Git uses ```.uses``` and ```.with``` on a ```.job``` level to run reusable workflows. [Read more here](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Factions%2Fusing-workflows%2Fworkflow-syntax-for-github-actions%23jobsjob_iduses&data=05%7C01%7CMorne.VanZyl%40iwgplc.com%7C03ad5ec14d1448b011e708db3046b919%7C88155c28f750401391d38347ddb3daa7%7C0%7C0%7C638156852530322959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vtnSrv0BOu7YCvtbbBZ1muZm7B3LQv58Ug1YdHiUd3g%3D&reserved=0)
 
Git uses the ```.run``` directive on their ```.steps``` (for commands, tasks or action in your repo/public repo/Docker registry) [Read more here](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Factions%2Fusing-workflows%2Fworkflow-syntax-for-github-actions%23jobsjob_idsteps&data=05%7C01%7CMorne.VanZyl%40iwgplc.com%7C03ad5ec14d1448b011e708db3046b919%7C88155c28f750401391d38347ddb3daa7%7C0%7C0%7C638156852530322959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qHEXm7ppV34Vseumak%2BMn51FCPXLizfjXvSN4gmfXZs%3D&reserved=0)
 
Nox uses ```.uses``` (to invoke Nox.Cli.Plugins) and ```.with``` (to pass parameters to plugin) on a .step level.
 
From what I can see, Nox doesn’t use the ```.run``` directive in its workflows.

**Comment by jan-schutte** [comment]
Thanks for the review @Mornevanzyl  for now we will stick with the cli workflow structure we have
