### ISSUE TITLE
[Nox.Lib] Service -> Solution: Change to allow configuration file to support [name].solution.nox.yaml

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox.Lib.V6#181]
Allow Nox.Lib to accept [your_solution_name].**solution**.nox.yaml file naming and be backwards compatible to still accept [your_solution_name].**service**.nox.yaml files.

**Comment by Mornevanzyl** [comment]
- Andre suggested we do the required YAML change and then we do a full review of all the documentation and change all references from service to solution.
- Andre said he'll work on this with Oleks and Jan.
- Suggested backwards-compatibility to still support sevice.nox.yaml files, although deprecation might be considered.

**Comment by jan-schutte** [comment]
This has been superceded  by Nox.Configuration
