### ISSUE TITLE
[Nox.Lib] Message Listener/Consumer - YAML configuration issues for consideration

### ISSUE THREAD

**Issue by Mornevanzyl** [NoxOrg/Nox.Lib.V6#182]
- Service/Solution configuration file currently relies on DB connection properties to be declared. Should probably/possibly be able to run without any knowledge of the database.
- Entity configuration files should probably support DTOs rather than DB properties.
- Message/Event/Command Handler vs. Consumer terminology

**Comment by jan-schutte** [comment]
Listeners can easily consume contracts from an api using a dll or perhaps reading metadata from the api endpoint.
Listeners should not have to declare a database in yaml config if the yaml definition is used.

**Comment by jan-schutte** [comment]
Resolved by Nox.Configuration
