### ISSUE TITLE
Implement ${ENV_VARIABLE_NAME}

### ISSUE THREAD

**Issue by andresharpe** [NoxOrg/Nox.Lib.V6#87]
- Remove ConnectionStringVariable and replace with ${ENV_VARIABLE_NAME}
- Inject secrets/env variable (i.e. IConfiguration keys) into YAML before deserializing
- Should take care of secrets in MessagingProvider

**Comment by rochar** [comment]
I do have a branch, already review by @andresharpe , that support defining Environment Variables, this needs to be enhanced to support other type of configurations like secrets, and the PR needs to be cherry pick to Nox.Solution. See also issue https://github.com/NoxOrg/Nox.Solution/issues/7

**Comment by rochar** [comment]
duplicated from https://github.com/NoxOrg/Nox.Solution/issues/7
